export const importTexts = {
  locale: 'cs-CZ', title: 'Import dat', select: 'Vyberte soubor', upload: 'Nahrát soubor',
  empty: 'Vyberte soubor pro import.', uploading: 'Nahrávání souboru…', loading: 'Načítání…',
  validate: 'Spustit validaci', start: 'Spustit import', retry: 'Znovu načíst stav',
  replace: 'Opravit soubor a nahrát znovu', newImport: 'Nový import',
  file: 'Soubor', filename: 'Název', size: 'Velikost', uploadedAt: 'Datum nahrání', bytes: 'B',
  validation: 'Validace', totalRecords: 'Celkem záznamů', valid: 'Validních', invalid: 'Chybných',
  errors: 'Chyby', table: 'Tabulka', row: 'Řádek', field: 'Pole', value: 'Hodnota', reason: 'Chyba', severity: 'Závažnost',
  noErrors: 'Žádné chyby.', previous: 'Předchozí', next: 'Další', retryErrors: 'Znovu načíst chyby',
  page: (page: number, total: number) => `Stránka ${page} z ${total}`,
  errorCount: (count: number) => `Celkem chyb: ${count}`,
  importing: 'Import', processed: 'Počet zpracovaných', successful: 'Počet úspěšných', failed: 'Počet chybných',
  completed: 'IMPORT DOKONČEN', total: 'Celkem', imported: 'Imported', skipped: 'Skipped', failedFinal: 'Failed',
  unavailableValue: 'Není k dispozici',
  missingStatistics: 'Backend zatím neposkytuje počty zpracovaných, přeskočených a neúspěšných záznamů.',
  uploadDateNote: 'Backend poskytuje datum založení importu; samostatné datum nahrání zatím není k dispozici.',
  createdAt: 'Datum založení importu',
  validationFailed: 'Validace selhala. Opravte chyby v souboru a nahrajte jej znovu.',
  serverUnavailable: 'Server není dostupný. Zkuste znovu načíst stav.',
  requestFailed: 'Požadavek se nezdařil. Načtěte aktuální stav před dalším pokusem.',
  unauthorized: 'Přihlášení vypršelo nebo nemáte oprávnění k importu.',
  errorsFailed: 'Seznam chyb se nepodařilo načíst.',
  status: {
    CREATED: 'Import založen', UPLOADED: 'Soubor nahrán', VALIDATING: 'Probíhá validace…',
    VALID: 'Validace úspěšná', INVALID: 'Validace neúspěšná', READY: 'Připraveno k importu',
    IMPORTING: 'Probíhá import…', COMPLETED: 'Import dokončen',
    COMPLETED_WITH_ERRORS: 'Import dokončen s chybami', FAILED: 'Import selhal',
  },
};
